apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "springboot-helm.fullname" . }}
  labels:
    {{- include "springboot-helm.labels" . | nindent 4 }}
spec:
  host: {{ include "springboot-helm.fullname" . }}.apps.lab01.gpslab.club
  to:
    kind: Service
    name:  {{ include "springboot-helm.fullname" . }}

